
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 13:07:12 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 48;
  public static final int CONST = 19;
  public static final int NAMESPACE = 26;
  public static final int NOTEQUAL = 33;
  public static final int HASH = 49;
  public static final int LPAREN = 6;
  public static final int GREATER = 34;
  public static final int SEMI = 5;
  public static final int CONTINUE = 24;
  public static final int LESS = 36;
  public static final int FOR = 27;
  public static final int STATIC = 25;
  public static final int RPAREN = 7;
  public static final int AND = 38;
  public static final int LESSEQUAL = 37;
  public static final int OR = 39;
  public static final int BOOL = 47;
  public static final int COMMA = 11;
  public static final int CLASS = 17;
  public static final int INC = 40;
  public static final int EQUALEQUAL = 32;
  public static final int DIV = 30;
  public static final int PLUS = 10;
  public static final int IF = 20;
  public static final int DOT = 43;
  public static final int DOTS = 42;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int NUMBER = 14;
  public static final int MOD = 31;
  public static final int BREAK = 16;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int GREATEREQUAL = 35;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int LSQUARE = 44;
  public static final int READ = 22;
  public static final int RSQUARE = 45;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 23;
  public static final int PROG = 2;
  public static final int DEC = 41;
  public static final int POINTER = 46;
  public static final int MAX = 50;
  public static final int SUB = 28;
  public static final int PRINT = 12;
}

